spring:
  config:
    import: optional:file:.env[.properties]


  application:
    name: rule-engine

logging:
  level:
    com.nhnacademy.ruleengine: DEBUG
    com.influx-db: INFO


rule-engine:
  mqtt:
    external:
      broker-url: tcp://10.116.64.13:1883
      client-id-prefix: rule-engine-subscriber
      topic: application/+/device/+/event/up
      qos: 1

    internal:
      broker-url: tcp://mosquitto:1883
      client-id-prefix: rule-engine-internal-publisher
      topic-prefix: iot
      qos: 1

influx-db:
  url: ${INFLUX_URL}
  token: ${INFLUX_TOKEN}
  org: ${INFLUX_ORG}
  bucket: ${INFLUX_BUCKET}
  measurement: ${INFLUX_MEASUREMENT}

server:
  port: 10406

management:
  endpoints:
    web:
      exposure:
        include: health, service-registry
  endpoint:
    health:
      show-details: never