spring:
  config:
    import: optional:file:.env[.properties]


  application:
    name: rule-engine

  data:
   redis:
     host: ${REDIS_HOST}
     port: ${REDIS_PORT}
     password: ${REDIS_PASSWORD}
     database: ${REDIS_DATABASE}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 10


logging:
  level:
    com.nhnacademy.ruleengine: INFO
    com.influx-db: INFO

rule-engine:
  inventory:
    base-url: lb://inventory

  redundancy:
    instance-id: ${INSTANCE_ID}
    external-ingress:
      lock-key: rule-engine:lock:external-ingress
      lease-duration: 10s
      renew-interval: 3s

    virtual-sensor:
      lock-key: rule-engine:lock:virtual-sensor
      lease-duration: 10s
      renew-interval: 3s

  mqtt:
    external:
      broker-url: tcp://10.116.64.13:1883
      client-id-prefix: rule-engine-subscriber
      topic: application/+/device/+/event/up
      qos: 1

influx-db:
  url: ${INFLUX_URL}
  token: ${INFLUX_TOKEN}
  org: ${INFLUX_ORG}
  bucket: ${INFLUX_BUCKET}
  measurement: ${INFLUX_MEASUREMENT}

server:
  port: ${SERVER_PORT:10406}

management:
  endpoints:
    web:
      exposure:
        include: health, service-registry
  endpoint:
    health:
      show-details: never

notification:
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN}
    api-base-url: https://api.telegram.org
  kakao-talk:
    client-id: ${KAKAOTALK_REST_API_KET}
    api-base-url: https://kapi.kakao.com
    access-token: ${KAKAOTALK_ACCESS_TOKEN}