eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

logging:
  level:
    com.nhnacademy.ruleengine: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, service-registry, prometheus
  tracing:
    export:
      zipkin:
        endpoint: ${ZIPKIN_ENDPOINT}

security:
  jwt:
    jwk-set-uri: http://team1-account-1:10413/.well-known/jwks.json