eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

logging:
  level:
    com.nhnacademy.ruleengine: INFO

management:
  tracing:
    export:
      zipkin:
        endpoint: ${ZIPKIN_ENDPOINT}