eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: >-
        http://team1-eureka-1:10402/eureka/,
        http://team1-eureka-2:10403/eureka/

logging:
  level:
    com.nhnacademy.ruleengine: INFO