@host = http://localhost:10406

### 가상데이터 생성 Flow 생성
POST {{host}}/api/rule-engine/organizations/2/storages/1/zones/24/virtual-sensor
Content-Type: application/json

{
  "temperature": {
    "min": 25,
    "max": 26
  },
  "humidity": {
    "min": 50,
    "max": 55
  },
  "illumination": {
    "min": 100,
    "max": 150
  },
  "doorOpenProbability": 0.01,
  "measurementIntervalSeconds": 60,
  "deviceEui": "device-eui-virtual-24"
}

### 가상데이터 생성정보 조회
GET {{host}}/api/rule-engine/organizations/2/storages/1/zones/24/virtual-sensor

### 가상데이터 생성정보 변경
PUT {{host}}/api/rule-engine/organizations/2/storages/1/zones/24/virtual-sensor
Content-Type: application/json

{
  "temperature": {
    "min": 20,
    "max": 30
  }
}

### 가상데이터 생성정보 삭제
DELETE {{host}}/api/rule-engine/organizations/2/storages/1/zones/23/virtual-sensor


### Zone에서 Flow 정지
PUT {{host}}/api/rule-engine/organizations/2/storages/1/zones/24/status
Content-Type: application/json

{
  "status": "INACTIVE"
}

### Zone에서 Flow 다시시작
PATCH {{host}}/api/rule-engine/organizations/2/storages/1/zones/24/status
Content-Type: application/json

{
  "status": "ACTIVE"
}